# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
early_access: false
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  in_progress_fortune: true
  poem: false
  enable_prompt_for_ai_agents: true
  path_filters:
    - '!**/*.xml'
    - '!**/__generated__/**'
    - '!**/generated/**'
    - '!**/*.json'
    - '!**/*.svg'
    - '!**/*.png'
    - '!**/*.jpg'
    - '!**/*.gif'
    - '!**/*.lock'
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
