coverage:
  status:
    patch:
      default:
        enabled: true
        target: 90%
        threshold: 5%
    project:
      default:
        target: 90%
        threshold: 5%

comment:
  layout: 'header, diff, components'

ignore:
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/index.ts'
  - '**/index.tsx'
